---
version: '3.5'
services:

  mongodb:
    image: mongo:latest
    hostname: mongodb
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: debezium
      MONGO_INITDB_ROOT_PASSWORD: dbz
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "debezium" ]

  mongo-express:
    image: mongo-express:latest
    hostname: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 18081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: myuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: mypassword
      ME_CONFIG_MONGODB_URL: mongodb://myuser:mypassword@mongodb:27017/
      
  connect:
    depends_on:
      - zookeeper
      - broker
      - schema-registry
      - mongodb
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/debezium-debezium-connector-mongodb
