---
version: '3.5'
services:
  connect:
    volumes:
      - ../../connect/connect-jdbc-azure-synapse-analytics-source/data:/data
      - ../../connect/connect-jdbc-azure-synapse-analytics-source/sqljdbc_12.2/enu/mssql-jdbc-12.2.0.jre11.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/lib/mssql-jdbc-12.2.0.jre11.jar
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc
