
---
version: '3.5'
services:

  squid:
    image: ubuntu/squid
    hostname: squid
    container_name: squid
    ports:
      - "8888:8888"
    volumes:
      - ../../connect/connect-pagerduty-sink/squid/passwords:/etc/squid/passwords
      - ../../connect/connect-pagerduty-sink/squid/squid.conf:/etc/squid/squid.conf

  connect:
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-pagerduty
    dns: 0.0.0.0