---
version: '3.5'
services:

  connect:
    ports:
      - "5439:5439"
    depends_on:
      - zookeeper
      - broker
      - schema-registry
    volumes:
        - ../../connect/connect-jdbc-aws-redshift-source/redshift-jdbc42-2.1.0.17/redshift-jdbc42-2.1.0.17.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/lib/redshift-jdbc42-2.1.0.17.jar
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc