---
version: '3.5'
services:
  oracle:    
    image: wnameless/oracle-xe-11g-r2
    hostname: oracle
    container_name: oracle
    ports:
      - "1521:1521"
    volumes:
      - ../../ccloud/fully-managed-connect-cdc-oracle11-source/ora-setup-scripts/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ../../ccloud/fully-managed-connect-cdc-oracle11-source/ora-setup-scripts/02_init.sql:/docker-entrypoint-initdb.d/02_init.sql
    environment:
      ORACLE_ALLOW_REMOTE: "true"

  # https://ngrok.com/docs/using-ngrok-with/docker/
  ngrok:
    image: ngrok/ngrok:latest
    hostname: ngrok
    container_name: ngrok
    ports:
      - 4040:4040
    restart: unless-stopped
    links:
      - oracle
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ../../ccloud/fully-managed-connect-cdc-oracle11-source/ngrok.yml:/etc/ngrok.yml
    environment:
      NGROK_AUTHTOKEN: $NGROK_AUTH_TOKEN