---
version: '3.5'
services:

  # getting weird "Couldn't create directory: Failure", so created image from this PR https://github.com/atmoz/sftp/pull/164
  # https://github.com/amaysim-au/docker-sftp/tree/chroot-user
  # docker build -t vdesabou/sftp .
  # docker push vdesabou/sftp
  sftp-server:
    image: vdesabou/sftp
    hostname: sftp-server
    container_name: sftp-server
    ports:
      - "2222:22"
    command: foo:pass:::upload

  # https://github.com/shkoliar/docker-ngrok
  ngrok:
    image: shkoliar/ngrok:latest
    hostname: ngrok
    container_name: ngrok
    ports:
      - 4551:4551
    links:
      - sftp-server
    environment:
      DOMAIN: sftp-server
      PORT: 22
      PROTOCOL: tcp
      REGION: eu
      AUTH_TOKEN: $NGROK_AUTH_TOKEN
      DEBUG: "true"