---
version: '3.5'
services:
  prometheus-server:
    image: prom/prometheus:v2.11.1
    hostname: prometheus-server
    container_name: prometheus-server
    ports:
      - 19090:9090
    volumes:
      - ../../connect/connect-prometheus-sink/prometheus:/etc/prometheus/

  connect:
    depends_on:
      - prometheus-server
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-prometheus-metrics