name: Update README

on:
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: vdesabou/kafka-docker-playground
          fetch-depth: 0
          submodules: recursive
          ssh-key: ${{ secrets.GH_SSH_KEY_FILE }}
          ssh-strict: 'false'

      - name: Update README
        run: |
          ./scripts/update-readme.sh "6.0.13 6.1.10 6.2.9 7.0.8 7.1.6 7.2.4 7.3.3"
        env:
          GH_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}

      - name: Pushes content.md
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.CI_GITHUB_TOKEN }}
        with:
          source_file: './docs/content.md'
          destination_repo: 'vdesabou/kafka-docker-playground-docs'
          destination_folder: 'docs'
          user_email: 'vincent.desaboulin@gmail.com'
          user_name: 'vdesabou'
          commit_message: 'updating with latest versions'

      - name: Pushes introduction.md
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.CI_GITHUB_TOKEN }}
        with:
          source_file: './docs/introduction.md'
          destination_repo: 'vdesabou/kafka-docker-playground-docs'
          destination_folder: 'docs'
          user_email: 'vincent.desaboulin@gmail.com'
          user_name: 'vdesabou'
          commit_message: 'updating with latest versions'